# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NOKOUT
email: bogus4now@domain.com
description: My Ramblings

baseurl: "" #e.g. /safarnama, /blog. Dont forget the '/'.
url: "http://nokout.github.io" # the base hostname & protocol for your site
twitter_username: nokout_
github_username:  nokout

# Build settings
markdown: kramdown
